services:
  php-apache:
    #image: php-apache
    container_name: php-apache_container
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PHP_HOST: ${PHP_HOST}
      PHP_PORT: ${PHP_PORT}
    ports:
      - "${PHP_PORT}:80"
    # This variant copy ALL CURRENT data to /var/www/html
    #volumes:
    #  - .:/var/www/html
    # Add environment variables if needed
    # environment:
    #   - VARIABLE_NAME=value
  qr-apache:
    #image: php-apache
    container_name: qr-apache_container
    build:
      context: ./qr
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PHP_HOST: ${PHP_HOST}
      PHP_PORT: ${PHP_PORT}
      QR_HOST: ${PHP_HOST}
      QR_PORT: ${QR_PORT}
    ports:
      - "${QR_PORT}:80"
  db:
    image: postgres
    container_name: database_container
    hostname: ${DB_HOST}
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    #restart: always
    # set shared memory limit when using docker-compose
    #shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    healthcheck:
      #test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
    #      memory: 4G
    #networks:
    #  - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    #networks:
    #  - kafka_networks
volumes:
  db-data:
  pgadmin-data:
